### ISSUE TITLE
ROUTING ON BACKEND

### ISSUE THREAD

**Issue by inuoluwadunsimi** [hacetheworld/ecommerce-store#9]
Hi, on the 17th line of the code for auth.js after the validation for user exists goes through, isn't it meant to route to the login or is that handled on the frontend?

**Comment by ethAmazinDor** [comment]
hey i was wondering is there any additional info on this ?

**Comment by hacetheworld** [comment]
Hey @inuoluwadunsimi @ethAmazinDor , it's been 2 years since i updated this project so i'm not really sure about functionality of this project .
